/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.24.0-644-g4c704ecfd (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.24.0-644-g4c704ecfd"
#endif
#define SDL_REVISION_NUMBER 0
